#!/system/bin/sh

#CPU
echo'2100000 1300000' > /sys/devices/system/cpu/cpufreq/mp-cpufreq/cpu_volt_table
echo'2000000 1262500' > /sys/devices/system/cpu/cpufreq/mp-cpufreq/cpu_volt_table
echo'1900000 1175000' > /sys/devices/system/cpu/cpufreq/mp-cpufreq/cpu_volt_table
echo'1800000 1100000' > /sys/devices/system/cpu/cpufreq/mp-cpufreq/cpu_volt_table
echo'1700000 1087500' > /sys/devices/system/cpu/cpufreq/mp-cpufreq/cpu_volt_table
echo'1600000 1037000' > /sys/devices/system/cpu/cpufreq/mp-cpufreq/cpu_volt_table
echo'1500000 1000000' > /sys/devices/system/cpu/cpufreq/mp-cpufreq/cpu_volt_table
echo'1400000 975000' > /sys/devices/system/cpu/cpufreq/mp-cpufreq/cpu_volt_table
echo'1300000 950000' > /sys/devices/system/cpu/cpufreq/mp-cpufreq/cpu_volt_table
echo'1200000 925000' > /sys/devices/system/cpu/cpufreq/mp-cpufreq/cpu_volt_table
echo'1100000 900000' > /sys/devices/system/cpu/cpufreq/mp-cpufreq/cpu_volt_table
echo'1000000 900000' > /sys/devices/system/cpu/cpufreq/mp-cpufreq/cpu_volt_table
echo'900000 900000' > /sys/devices/system/cpu/cpufreq/mp-cpufreq/cpu_volt_table
echo'800000 900000' > /sys/devices/system/cpu/cpufreq/mp-cpufreq/cpu_volt_table
echo'700000 900000' > /sys/devices/system/cpu/cpufreq/mp-cpufreq/cpu_volt_table
echo'600000 875000' > /sys/devices/system/cpu/cpufreq/mp-cpufreq/cpu_volt_table
echo'500000 875000' > /sys/devices/system/cpu/cpufreq/mp-cpufreq/cpu_volt_table
echo'400000 875000' > /sys/devices/system/cpu/cpufreq/mp-cpufreq/cpu_volt_table
echo'1400000 1100000' > /sys/devices/system/cpu/cpufreq/mp-cpufreq/kfc_volt_table
echo'1300000 1050000' > /sys/devices/system/cpu/cpufreq/mp-cpufreq/kfc_volt_table
echo'1200000 1025000' > /sys/devices/system/cpu/cpufreq/mp-cpufreq/kfc_volt_table
echo'1100000 1000000' > /sys/devices/system/cpu/cpufreq/mp-cpufreq/kfc_volt_table
echo'1000000 1000000' > /sys/devices/system/cpu/cpufreq/mp-cpufreq/kfc_volt_table
echo'900000 950000' > /sys/devices/system/cpu/cpufreq/mp-cpufreq/kfc_volt_table
echo'800000 925000' > /sys/devices/system/cpu/cpufreq/mp-cpufreq/kfc_volt_table
echo'700000 925000' > /sys/devices/system/cpu/cpufreq/mp-cpufreq/kfc_volt_table
echo'600000 900000' > /sys/devices/system/cpu/cpufreq/mp-cpufreq/kfc_volt_table
echo'500000 900000' > /sys/devices/system/cpu/cpufreq/mp-cpufreq/kfc_volt_table
echo'400000 900000' > /sys/devices/system/cpu/cpufreq/mp-cpufreq/kfc_volt_table